force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AccOwnerId__c.field-meta.xml
<CustomField>
    <fullName>AccOwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of an account against which transaction is executed</description>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Creation_Time__c.field-meta.xml
<CustomField>
    <fullName>Creation_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Creation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Purpose of the transaction</description>
    <label>Purpose</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>User&apos;s current balance according to his transactions</description>
    <label>Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TransactionTriggersTest.cls
@isTest
private class TransactionTriggersTest {
    
    @isTest
    static void testInsertTime() {
        Id userId = UserInfo.getUserId();
        Transaction__c t = new Transaction__c(Amount__c=120,Purpose__c='test', AccOwnerId__c = userId);
        
        Test.startTest();
        insert t;
        t = [SELECT Creation_Time__c FROM Transaction__c WHERE Id=:t.Id][0];
        Test.stopTest();
        
        System.assert(t.Creation_Time__c != null);
    }
    
    @isTest
    static void testTransactionInsert() {
        Test.startTest();
        User usr = TestDataProvider.generateUser('Standard User');

        List<Transaction__c> trans = TestDataProvider.getUserTransactions(usr.Id, 10);
        insert trans;
        
        usr = [SELECT Balance__c FROM User WHERE Id=:usr.Id LIMIT 1];
        
        Test.stopTest();
        
        System.assertEquals(usr.Balance__c, 10 * TestDataProvider.DEFAULT_AMOUNT);

    }
    
    
    @isTest
    static void testTransactionUpdate() {
        Test.startTest();
        User usr = TestDataProvider.generateUser('Standard User');

        List<Transaction__c> trans = TestDataProvider.getUserTransactions(usr.Id, 10);
        insert trans;
        
        Transaction__c t = trans[0];
        t.Amount__c = TestDataProvider.DEFAULT_AMOUNT + 20;
        update t;
        
        usr = [SELECT Balance__c FROM User WHERE Id=:usr.Id LIMIT 1];
        
        Test.stopTest();
        
        System.assertEquals(usr.Balance__c, 10 * TestDataProvider.DEFAULT_AMOUNT + 20);

    }
    
    @isTest
    static void testTransactionDelete() {
        User usr = TestDataProvider.generateUser('Standard User');
        
        Test.startTest();
        
        List<Transaction__c> trans = TestDataProvider.getUserTransactions(usr.Id, 10);
        insert trans;
        
        Transaction__c t = trans[0];
        delete t;
        
        usr = [SELECT Balance__c FROM User WHERE Id=:usr.Id LIMIT 1];
        
        Test.stopTest();
        
        System.assertEquals(usr.Balance__c, 9 * TestDataProvider.DEFAULT_AMOUNT);

    }
}