force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AccOwnerId__c.field-meta.xml
<CustomField>
    <fullName>AccOwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of an account against which transaction is executed</description>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Purpose of the transaction</description>
    <label>Purpose</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestTransactionHelper.cls
@isTest
private class TestTransactionHelper {
    @isTest
    static void testHelper() {
        User usr = TestDataProvider.getUser();
        
        Test.startTest();
        insert usr;
        
        Transaction__c t1 = new Transaction__c(Amount__c=100, Purpose__c='Test', AccOwnerId__c=usr.Id);
        Transaction__c t2 = new Transaction__c(Amount__c=100, Purpose__c='Test', AccOwnerId__c=usr.Id);
        insert new List<Transaction__c>{t1,t2};
            
        List<Transaction__c> trans = TransactionHelper.getUserTransactions(usr.Id);
        Test.stopTest();
        
        System.assertEquals(2, trans.size());
    }
}