force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AccOwnerId__c.field-meta.xml
<CustomField>
    <fullName>AccOwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of an account against which transaction is executed</description>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Purpose of the transaction</description>
    <label>Purpose</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>User&apos;s current balance according to his transactions</description>
    <label>Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestDataProvider.cls
public with sharing class TestDataProvider {
    public static final Integer DEFAULT_AMOUNT = 100;
    public static User generateUser(String profileName) {
         Profile profileId = [SELECT Id FROM Profile WHERE Name =: profileName LIMIT 1];

		 User usr = new User(LastName = 'LIVESTON',
                   FirstName='JASON',
                   Alias = 'jliv',
                   Email = 'jason.liveston@asdf.com',
                   Username = 'testuser1984@test.com',
                   ProfileId = profileId.id,
                   TimeZoneSidKey = 'GMT',
                   LanguageLocaleKey = 'en_US',
                   CommunityNickname = 'wlef,lwfe,lw',
                   EmailEncodingKey = 'UTF-8',
                   LocaleSidKey = 'en_US',
                   Balance__c = 0
                   );
        
        insert usr;

        return usr;
        
    }
    
    public static List<Transaction__c> getUserTransactions(Id userId, Integer count) {
        List<Transaction__c> transactions = new List<Transaction__c>();
        
        for(Integer i = 0; i < count; i++) {
            Transaction__c t = new Transaction__c(Amount__c = DEFAULT_AMOUNT, AccOwnerId__c = userId, Purpose__c='Test purpose');
            transactions.add(t);
        }
        
        return transactions;
    }

    public static void assignPermissionSet(Id userId, String permSetLabel) {
        PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Label=:permSetLabel][0];

        PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = permSet.Id, AssigneeId = userId);
        insert psa;  
    }
}