force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AccOwnerId__c.field-meta.xml
<CustomField>
    <fullName>AccOwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of an account against which transaction is executed</description>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Creation_Time__c.field-meta.xml
<CustomField>
    <fullName>Creation_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Creation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Purpose of the transaction</description>
    <label>Purpose</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TransactionHelper.cls
public with sharing class TransactionHelper {

    @AuraEnabled(cacheable=true)
    public static List<Transaction__c> getUserTransactions(Id userId) {
        List<Transaction__c> transactions = [SELECT AccOwnerId__c, Amount__c, Purpose__c FROM Transaction__c WHERE AccOwnerId__c=:userId ORDER BY Creation_Time__c DESC];
        
        SObjectAccessDecision decision;
        try {
            decision = Security.stripInaccessible( // also checks object-level access, if fails -> NoAccessException
            AccessType.UPDATABLE,
            transactions);
        } catch(NoAccessException e) {
            throw new AuraHandledException('You have no access to Transaction object (' + e.getMessage() + ')');  
        }

        return (List<Transaction__c>) decision.getRecords();
    }
}